### ISSUE TITLE
Code 97, 41017, 30167 Error

### ISSUE THREAD

**Issue by dltmddbs100** [taeminlee/tomok2md#1]
교량 파트의 Code 97, 41017, 30167에서 발생하는 에러 로그입니다.

## 97
2023-09-27 15:13:10 [info     ] READ ./files/97.json
2023-09-27 15:13:10 [info     ] CONVERT ./files/97.json => ./files/97.md

  0%|          | 0/16 [00:00<?, ?it/s]
  0%|          | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "kds2md.py", line 77, in <module>
    fire.Fire(kds2md)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "kds2md.py", line 51, in kds2md
    doc_md = html2md.html2md(doc_fragment)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 16, in __init__
    self.make_md(html_str, parser)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 22, in make_md
    self.title = self.get_title()
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 308, in get_title
    self.level = int(title_tree.xpath('./a')[0].get('data-level'))
IndexError: list index out of range

## 30167
2023-09-27 15:13:10 [info     ] READ ./files/30167.json
2023-09-27 15:13:10 [info     ] CONVERT ./files/30167.json => ./files/30167.md

  0%|          | 0/94 [00:00<?, ?it/s]
 10%|▉         | 9/94 [00:00<00:01, 67.30it/s]
 11%|█         | 10/94 [00:00<00:01, 70.14it/s]
Traceback (most recent call last):
  File "kds2md.py", line 77, in <module>
    fire.Fire(kds2md)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "kds2md.py", line 51, in kds2md
    doc_md = html2md.html2md(doc_fragment)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 16, in __init__
    self.make_md(html_str, parser)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 22, in make_md
    self.title = self.get_title()
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 308, in get_title
    self.level = int(title_tree.xpath('./a')[0].get('data-level'))
IndexError: list index out of range

## 41017
2023-09-27 15:13:10 [info     ] READ ./files/41017.json
2023-09-27 15:13:10 [info     ] CONVERT ./files/41017.json => ./files/41017.md

  0%|          | 0/106 [00:00<?, ?it/s]
  8%|▊         | 8/106 [00:00<00:00, 151.43it/s]
Traceback (most recent call last):
  File "kds2md.py", line 77, in <module>
    fire.Fire(kds2md)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/else/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "kds2md.py", line 51, in kds2md
    doc_md = html2md.html2md(doc_fragment)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 16, in __init__
    self.make_md(html_str, parser)
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 22, in make_md
    self.title = self.get_title()
  File "/home/data/dltmddbs100/tomok2md/html2md.py", line 310, in get_title
    title_md = '#' * self.level + ' ' + title_tree.xpath('./a')[0].text
TypeError: can only concatenate str (not "NoneType") to str

**Comment by taeminlee** [comment]
html 태그가 올바르지 않은 경우에도 파싱 하도록 일부 수정하였습니다.

```bash
(tomok) persuade@nlp-server-10:/mnt/md0/persuade/tomok/tomok2md$ python kds2md.py --code=97
2023-10-06 18:58:04 [info     ] READ 97.json
2023-10-06 18:58:04 [info     ] CONVERT 97.json => 97.md
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 125.61it/s]
2023-10-06 18:58:05 [info     ] SAVE INTO 97.md
2023-10-06 18:58:05 [info     ] SAVE INTO 97_chunks.json
2023-10-06 18:58:05 [info     ] DONE
(tomok) persuade@nlp-server-10:/mnt/md0/persuade/tomok/tomok2md$ python kds2md.py --code=41017
2023-10-06 18:58:07 [info     ] READ 41017.json
2023-10-06 18:58:07 [info     ] CONVERT 41017.json => 41017.md
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [00:00<00:00, 459.60it/s]
2023-10-06 18:58:07 [info     ] SAVE INTO 41017.md
2023-10-06 18:58:07 [info     ] SAVE INTO 41017_chunks.json
2023-10-06 18:58:07 [info     ] DONE
(tomok) persuade@nlp-server-10:/mnt/md0/persuade/tomok/tomok2md$ python kds2md.py --code=30167
2023-10-06 18:58:18 [info     ] DOWNLOAD 30167
2023-10-06 18:58:20 [info     ] CONVERT 30167.json => 30167.md
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 94/94 [00:00<00:00, 124.23it/s]
2023-10-06 18:58:21 [info     ] SAVE INTO 30167.md
2023-10-06 18:58:21 [info     ] SAVE INTO 30167_chunks.json
2023-10-06 18:58:21 [info     ] DONE
```

**Comment by taeminlee** [comment]
https://github.com/taeminlee/tomok2md/commit/eadfa4d2cd4e2b02da47f1ddb41db8a28b28cbb8
에 반영
